# Flight.create(status: "On Time", airline: "American Airlines", boarding_time: Time.now + 2.days, departure_airport: "SNA", arrival_airport: "MIA", departure_time: Time.now + 2.days + 1.hour, arrival_time: Time.now + 3.days)
# Flight.create(status: "Cancelled", airline: "United Airlines", boarding_time: Time.now + 10.days, departure_airport: "RSW", arrival_airport: "ORD", departure_time: Time.now + 10.days + 1.hour, arrival_time: Time.now + 10.days + 3.hours)
# Flight.create(status: "Departed", airline: "American Airlines", boarding_time: Time.now - 1.day, departure_airport: "ORD", arrival_airport: "DFW", departure_time: Time.now - 1.day + 1.hour, arrival_time: Time.now)

# User.create(first_name: "Sinan", last_name: "Fun", email: "funs@funny.com", phone_number: "123-456-7891")

# User.create(first_name: "Big", last_name: "Boss", email: "bigboss@noneofyourbusiness.com", phone_number: '123-456-7890')



Flight.create(status: "On Time", airline: "American Airlines", boarding_time: Time.now + 1.day, departure_airport: "DEN", arrival_airport: "JFK", departure_time: Time.now + 1.day + 1.hour, arrival_time: Time.now + 1.day + 5.hours)
Flight.create(status: "On Time", airline: "American Airlines", boarding_time: Time.now + 1.day, departure_airport: "MIA", arrival_airport: "BOS", departure_time: Time.now + 2.days + 1.hour, arrival_time: Time.now + 1.day + 5.hours)
Flight.create(status: "On Time", airline: "United Airlines", boarding_time: Time.now + 4.days, departure_airport: "DTW", arrival_airport: "PHL", departure_time: Time.now + 4.days + 1.hour, arrival_time: Time.now + 4.days + 4.hours)
Flight.create(status: "Cancelled", airline: "United Airlines", boarding_time: Time.now + 5.days, departure_airport: "SEA", arrival_airport: "PHX", departure_time: Time.now + 5.days + 1.hour, arrival_time: Time.now + 5.days + 4.hours)
Flight.create(status: "Cancelled", airline: "American Airlines", boarding_time: Time.now + 3.days, departure_airport: "SLC", arrival_airport: "SAN", departure_time: Time.now + 3.days + 1.hour, arrival_time: Time.now + 3.days + 3.hours)
Flight.create(status: "Delayed", airline: "American Airlines", boarding_time: Time.now + 2.days, departure_airport: "ORD", arrival_airport: "DFW", departure_time: Time.now + 2.days + 1.hour, arrival_time: Time.now + 2.days + 5.hours)
Flight.create(status: "Delayed", airline: "United Airlines", boarding_time: Time.now + 1.day, departure_airport: "TPA", arrival_airport: "HNL", departure_time: Time.now + 1.day + 1.hour, arrival_time: Time.now + 2.days)
Flight.create(status: "Delayed", airline: "United Airlines", boarding_time: Time.now + 6.days, departure_airport: "PDX", arrival_airport: "MDW", departure_time: Time.now + 6.days + 1.hour, arrival_time: Time.now + 6.days + 3.hours)
Flight.create(status: "On Time", airline: "United Airlines", boarding_time: Time.now + 1.day + 6.hours, departure_airport: "ORD", arrival_airport: "DEN", departure_time: Time.now + 1.day + 7.hours, arrival_time: Time.now + 1.day + 11.hours)
Flight.create(status: "Delayed", airline: "American Airlines", boarding_time: Time.now + 4.days, departure_airport: "SAN", arrival_airport: "MIA", departure_time: Time.now + 4.days + 1.hour, arrival_time: Time.now + 4.days + 3.hours)
Flight.create(status: "Delayed", airline: "United Airlines", boarding_time: Time.now + 6.days, departure_airport: "DFW", arrival_airport: "SLC", departure_time: Time.now + 6.days + 1.hour, arrival_time: Time.now + 6.days + 3.hours)
Flight.create(status: "Delayed", airline: "United Airlines", boarding_time: Time.now + 3.days, departure_airport: "LGA", arrival_airport: "FLL", departure_time: Time.now + 3.days + 1.hour, arrival_time: Time.now + 3.days + 5.hours)
Flight.create(status: "Delayed", airline: "United Airlines", boarding_time: Time.now + 2.days, departure_airport: "LAX", arrival_airport: "PDX", departure_time: Time.now + 2.days + 1.hour, arrival_time: Time.now + 2.days + 4.hours)
Flight.create(status: "Delayed", airline: "United Airlines", boarding_time: Time.now + 7.days, departure_airport: "BOS", arrival_airport: "DTW", departure_time: Time.now + 7.days + 1.hour, arrival_time: Time.now + 7.days + 3.hours)
Flight.create(status: "Cancelled", airline: "American Airlines", boarding_time: Time.now + 8.days, departure_airport: "LAS", arrival_airport: "MSP", departure_time: Time.now + 8.days + 1.hour, arrival_time: Time.now + 8.days + 6.hours)
Flight.create(status: "Cancelled", airline: "American Airlines", boarding_time: Time.now + 5.days, departure_airport: "ORD", arrival_airport: "IAH", departure_time: Time.now + 5.days + 1.hour, arrival_time: Time.now + 5.days + 4.hours)
Flight.create(status: "Delayed", airline: "American Airlines", boarding_time: Time.now + 9.days, departure_airport: "MDW", arrival_airport: "MCO", departure_time: Time.now + 9.days + 1.hour, arrival_time: Time.now + 9.days + 8.hours)
Flight.create(status: "Delayed", airline: "American Airlines", boarding_time: Time.now + 2.days, departure_airport: "HNL", arrival_airport: "CLT", departure_time: Time.now + 2.days + 1.hour, arrival_time: Time.now + 2.days + 5.hours)
Flight.create(status: "Delayed", airline: "American Airlines", boarding_time: Time.now + 8.days, departure_airport: "MSP", arrival_airport: "LAS", departure_time: Time.now + 8.days + 1.hour, arrival_time: Time.now + 8.days + 3.hours)
Flight.create(status: "Delayed", airline: "American Airlines", boarding_time: Time.now + 5.days, departure_airport: "FLL", arrival_airport: "LAX", departure_time: Time.now + 5.days + 1.hour, arrival_time: Time.now + 5.days + 6.hours)
Flight.create(status: "On Time", airline: "United Airlines", boarding_time: Time.now + 2.days, departure_airport: "PDX", arrival_airport: "JFK", departure_time: Time.now + 2.days + 1.hour, arrival_time: Time.now + 2.days + 5.hours)
Flight.create(status: "On Time", airline: "American Airlines", boarding_time: Time.now + 3.days, departure_airport: "LGA", arrival_airport: "MIA", departure_time: Time.now + 3.days + 1.hour, arrival_time: Time.now + 3.days + 5.hours)
Flight.create(status: "On Time", airline: "United Airlines", boarding_time: Time.now + 4.days, departure_airport: "LAX", arrival_airport: "LAS", departure_time: Time.now + 4.days + 1.hour, arrival_time: Time.now + 4.days + 4.hours)